### ISSUE TITLE
package.json 引入后 报编译错误，是啥情况？

### ISSUE THREAD

**Issue by phppm** [wuhao000/antd-mobile-vue#1]
ERROR  Failed to compile with 45 errors                                                                                                                                                     10:40:31

These relative modules were not found:

* ./api-proxy in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./global in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./http-method in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./loading-directive in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-accordion in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-action-sheet in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-activity-indicator in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-animate in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-badge in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-button in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-calendar in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-card in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-carousel in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-chart in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-checkbox in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-date-picker in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-drawer in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-flex in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-grid in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-icon in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-input in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-list in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-modal in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-nav-bar in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-notice-bar in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-pagination in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-picker in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-popup in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-pull-refresh in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-radio in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-range in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-result in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-search-bar in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-steps in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-switch in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-tab-bar in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-tabs in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-textarea in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-toast in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-white-space in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./m-wing-blank in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./menu in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./moment-zh_CN in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./slider in ./node_modules/ant-design-mobile-vue/src/packages/index.ts
* ./time-directive in ./node_modules/ant-design-mobile-vue/src/packages/index.ts

**Comment by phppm** [comment]
README文档里的引入说明不对

antd-mobile-vue 名称错了吧？ 应该是 ant-design-mobile-vue 吧

**Comment by wuhao000** [comment]
因为按需引入没有进行编译，引入的是ts文件，所以需要配置ts
