### ISSUE TITLE
按需引入编译失败

### ISSUE THREAD

**Issue by xxy1991** [wuhao000/antd-mobile-vue#2]
如果按文档说明，使用
`[
      "import",
      { libraryName: "antd-mobile-vue", libraryDirectory: "es", style: true },
      "antd-mobile-vue"
]`
则提示
> These dependencies were not found:
* antd-mobile-vue/es/toast in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Sale.vue?vue&type=script&lang=js&
* antd-mobile-vue/es/toast/style in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Sale.vue?vue&type=script&lang=js&

如果使用
`[
      "import",
      { libraryName: "antd-mobile", libraryDirectory: "es", style: true },
      "antd-mobile-vue"
]`
则提示
> These dependencies were not found:
* @/packages/tabs/src in ./node_modules/antd-mobile-vue/src/packages/vmc-drawer/index.tsx
* @/packages/tabs/src/utils in ./node_modules/antd-mobile-vue/src/packages/vmc-drawer/index.tsx
* @/packages/vmc-calendar/calendar-base in ./node_modules/antd-mobile-vue/src/packages/vmc-calendar/calendar-view.tsx, ./node_modules/antd-mobile-vue/src/packages/vmc-calendar/calendar.tsx

我看了下目录，没有对应文件。

**Comment by wuhao000** [comment]
按需引入的说明有误，已修改，项目并未将ts编译成js，所以引用的项目要有ts编译的相关配置
