### ISSUE TITLE
日期选择器列数据不会更新

### ISSUE THREAD

**Issue by Hult-Z** [wuhao000/antd-mobile-vue#8]
导致当设置了最大日期为30天后时，由于月份变了，日没有变，因此能选择到比最大日期还要大的日期。比如现在7月9日，设置了最大日期为一个月，按道理8月15日是无法被选择的，但是由于列数据没有刷新，当选择了8月时，日选择的数据还是9号到31号。

**Comment by wuhao000** [comment]
你描述的问题我并没有发现，参见示例 https://antdmobilevue.aegis-info.com/mobile-components/date-picker
